// Package docgen builds deterministic public references from executable SDBX
// metadata. Generated files are checked in so GitHub readers do not need Go
// tooling, while CI rejects drift from the command tree and embedded catalog.
package docgen

import (
	"bytes"
	"context"
	"fmt"
	"reflect"
	"sort"
	"strconv"
	"strings"

	sdbxcmd "github.com/get-sdbx/sdbx/cmd/sdbx/cmd"
	"github.com/get-sdbx/sdbx/internal/config"
	"github.com/get-sdbx/sdbx/internal/registry"
	"github.com/get-sdbx/sdbx/internal/registry/presets"
	"github.com/get-sdbx/sdbx/internal/settings"
	"gopkg.in/yaml.v3"
)

const generatedNotice = "<!-- Code generated by `go run ./cmd/sdbx-docgen --write`; DO NOT EDIT. -->\n\n"

// GenerateAll returns repository-relative output paths and complete file
// contents. Map iteration order is deliberately irrelevant to the output.
func GenerateAll() (map[string][]byte, error) {
	productManifest, err := generateProductManifest()
	if err != nil {
		return nil, err
	}
	cli, err := generateCLI()
	if err != nil {
		return nil, err
	}
	configuration, err := generateConfiguration()
	if err != nil {
		return nil, err
	}
	services, serviceNames, err := generateServices()
	if err != nil {
		return nil, err
	}
	presetReference, err := generatePresets(serviceNames)
	if err != nil {
		return nil, err
	}
	return map[string][]byte{
		"docs/configuration.md":      configuration,
		"docs/reference/cli.md":      cli,
		"docs/reference/presets.md":  presetReference,
		"docs/reference/services.md": services,
		"product-manifest.json":      productManifest,
	}, nil
}

func generateCLI() ([]byte, error) {
	reference := sdbxcmd.DocumentationCLIReference()
	if len(reference.Commands) == 0 {
		return nil, fmt.Errorf("Cobra command metadata is empty")
	}

	var output bytes.Buffer
	output.WriteString(generatedNotice)
	output.WriteString("# SDBX CLI Reference\n\n")
	output.WriteString(
		"This reference is generated from the Cobra command tree. " +
			"Run commands from an SDBX project directory unless the command " +
			"explicitly creates or discovers a project.\n\n",
	)
	output.WriteString("## Global options\n\n")
	writeFlagTable(&output, reference.GlobalFlags)
	output.WriteString(
		"\n`--json` is accepted only by commands marked **yes** below. " +
			"Runtime failures remain nonzero and emit one redacted error envelope.\n\n",
	)

	output.WriteString("## Command index\n\n")
	output.WriteString("| Command | Purpose | Runnable | JSON |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	for _, command := range reference.Commands {
		fmt.Fprintf(
			&output,
			"| [%s](#%s) | %s | %s | %s |\n",
			code(command.Path),
			markdownAnchor(command.Path),
			escapeTable(command.Short),
			yesNo(command.Runnable),
			yesNo(command.SupportsJSON),
		)
	}

	for _, command := range reference.Commands {
		fmt.Fprintf(&output, "\n## %s\n\n", command.Path)
		if command.Short != "" {
			fmt.Fprintf(&output, "%s\n\n", command.Short)
		}
		output.WriteString("```text\n")
		output.WriteString(command.UseLine)
		output.WriteString("\n```\n\n")
		if command.Runnable {
			fmt.Fprintf(
				&output,
				"- Machine-readable JSON: **%s**\n",
				yesNo(command.SupportsJSON),
			)
		} else {
			output.WriteString("- This is a command group; select a subcommand.\n")
		}
		flags := command.Flags
		if command.Path == "sdbx" {
			flags = nil
		}
		if len(flags) > 0 {
			output.WriteString("\n### Command options\n\n")
			writeFlagTable(&output, flags)
		}
	}
	return output.Bytes(), nil
}

func writeFlagTable(output *bytes.Buffer, flags []sdbxcmd.CLIReferenceFlag) {
	if len(flags) == 0 {
		output.WriteString("None.\n")
		return
	}
	output.WriteString("| Option | Type | Default | Status | Description |\n")
	output.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, flag := range flags {
		option := "--" + flag.Name
		if flag.Shorthand != "" {
			option = "-" + flag.Shorthand + ", " + option
		}
		status := "Current"
		if flag.Deprecated != "" {
			status = "Deprecated: " + flag.Deprecated
		} else if flag.Hidden {
			status = "Hidden compatibility option"
		}
		fmt.Fprintf(
			output,
			"| %s | %s | %s | %s | %s |\n",
			code(option),
			code(flag.Type),
			code(flag.Default),
			escapeTable(status),
			escapeTable(flag.Usage),
		)
	}
}

func generateConfiguration() ([]byte, error) {
	fields := settings.Fields()
	defaults := settings.Values(config.DefaultConfig())
	if len(fields) == 0 {
		return nil, fmt.Errorf("typed settings metadata is empty")
	}

	var output bytes.Buffer
	output.WriteString(generatedNotice)
	output.WriteString("# Configuration Reference\n\n")
	output.WriteString(
		"`.sdbx.yaml` is operator-owned project intent. The table below is " +
			"generated from the same typed setting metadata used by the CLI, " +
			"broker, and management UI.\n\n",
	)
	output.WriteString(
		"Use `sdbx config get` to inspect values and `sdbx config set KEY VALUE` " +
			"for one supported mutation. Each successful typed mutation validates " +
			"the complete configuration, updates the lock, and regenerates managed " +
			"runtime files.\n\n",
	)

	grouped := make(map[string][]settings.Field)
	var groups []string
	for _, field := range fields {
		if strings.TrimSpace(field.Description) == "" {
			return nil, fmt.Errorf("setting %s has no documentation description", field.Key)
		}
		if _, exists := defaults[field.Key]; !exists {
			return nil, fmt.Errorf("setting %s has no default/read value", field.Key)
		}
		if _, exists := grouped[field.Group]; !exists {
			groups = append(groups, field.Group)
		}
		grouped[field.Group] = append(grouped[field.Group], field)
	}
	for _, group := range groups {
		fmt.Fprintf(&output, "## %s\n\n", group)
		output.WriteString("| Key | Type | Default | Options | Typed mutation | Meaning |\n")
		output.WriteString("| --- | --- | --- | --- | --- | --- |\n")
		for _, field := range grouped[group] {
			options := "—"
			if len(field.Options) > 0 {
				options = strings.Join(field.Options, ", ")
			}
			fmt.Fprintf(
				&output,
				"| %s | %s | %s | %s | %s | %s |\n",
				code(field.Key),
				code(field.Type),
				code(formatValue(defaults[field.Key])),
				escapeTable(options),
				yesNo(field.Editable),
				escapeTable(field.Description),
			)
		}
		output.WriteString("\n")
	}

	defaultYAML, err := yaml.Marshal(config.DefaultConfig())
	if err != nil {
		return nil, fmt.Errorf("marshal default configuration: %w", err)
	}
	output.WriteString("## Generated default shape\n\n")
	output.WriteString(
		"This is the current serialized shape before the setup wizard replaces " +
			"placeholder choices. It is schema input, not a deployable unattended " +
			"configuration.\n\n```yaml\n",
	)
	output.Write(defaultYAML)
	output.WriteString("```\n\n")

	output.WriteString("## Direct HTTPS\n\n")
	output.WriteString(
		"Direct exposure supports ACME only in v1. The TLS provider is derived as " +
			"`acme`; `expose.tls.email` must contain one plain contact address. " +
			"Custom certificate-file fields are rejected because no supported " +
			"generator path consumes them.\n\n",
	)
	output.WriteString(
		"When changing an existing LAN or tunnel project, set the contact first, " +
			"then change the exposure mode:\n\n",
	)
	output.WriteString("```bash\n")
	output.WriteString("sdbx config set expose.tls.email ops@example.test\n")
	output.WriteString("sdbx config set expose.mode direct\n")
	output.WriteString("sdbx lock verify\n")
	output.WriteString("```\n\n")

	output.WriteString("## Service route overrides\n\n")
	output.WriteString(
		"`services` is a reviewed manual-intent map rather than a generic typed " +
			"setting. An entry may override `routing`, `subdomain`, or `path` for " +
			"one catalog service:\n\n",
	)
	output.WriteString("```yaml\n")
	output.WriteString("services:\n")
	output.WriteString("  sonarr:\n")
	output.WriteString("    routing: path\n")
	output.WriteString("    path: /television\n")
	output.WriteString("```\n\n")
	output.WriteString(
		"This map cannot override an image, environment variable, volume, " +
			"permission, network, or container policy. External source priority " +
			"selects a complete `kind: Service` definition under the source trust " +
			"rules; partial `kind: ServiceOverride` catalog documents are " +
			"rejected.\n\n",
	)
	output.WriteString(
		"After a manual edit, run `sdbx lock diff`, review the graph and route " +
			"change, then run `sdbx lock` and `sdbx lock verify`. Use `sdbx " +
			"generate` only when intent and the existing lock still agree.\n\n",
	)

	output.WriteString("## Path and credential rules\n\n")
	output.WriteString(
		"Relative managed paths must stay inside the project; absolute paths may " +
			"not be filesystem roots. Move several path roots in one reviewed YAML " +
			"edit so intermediate typed mutations do not create directories at an " +
			"old/new mixture.\n\n",
	)
	output.WriteString(
		"VPN usernames, passwords, private keys, tunnel tokens, claim tokens, " +
			"service API keys, and backup credentials do not belong in project " +
			"intent. A legacy `vpn_username` key is rejected with a migration " +
			"instruction; provider credentials belong in " +
			"`configs/gluetun/gluetun.env`.\n",
	)
	return output.Bytes(), nil
}

func generateServices() ([]byte, map[string]bool, error) {
	source := registry.NewEmbeddedSource()
	definitions, err := source.Load(context.Background())
	if err != nil {
		return nil, nil, fmt.Errorf("load embedded services: %w", err)
	}
	sort.Slice(definitions, func(i, j int) bool {
		return definitions[i].Metadata.Name < definitions[j].Metadata.Name
	})
	serviceNames := make(map[string]bool, len(definitions))
	core := make([]*registry.ServiceDefinition, 0)
	addons := make([]*registry.ServiceDefinition, 0)
	for _, definition := range definitions {
		if definition == nil {
			return nil, nil, fmt.Errorf("embedded catalog contains a nil definition")
		}
		if serviceNames[definition.Metadata.Name] {
			return nil, nil, fmt.Errorf("duplicate embedded service %s", definition.Metadata.Name)
		}
		serviceNames[definition.Metadata.Name] = true
		if definition.Conditions.RequireAddon {
			addons = append(addons, definition)
		} else {
			core = append(core, definition)
		}
	}

	var output bytes.Buffer
	output.WriteString(generatedNotice)
	output.WriteString("# Embedded Service Reference\n\n")
	fmt.Fprintf(
		&output,
		"The release binary contains **%d services**: **%d core definitions** "+
			"and **%d addons**. This inventory is generated from the embedded "+
			"catalog and changes only with the binary.\n\n",
		len(definitions),
		len(core),
		len(addons),
	)
	output.WriteString(
		"Image tags below are update-discovery inputs. Official first-run " +
			"locks use the release-reviewed embedded OCI snapshot; explicit " +
			"updates and external sources create new platform-specific locks. " +
			"Generated Compose files always use exact digests.\n\n",
	)
	writeServiceTable(&output, "Core definitions", core)
	writeServiceTable(&output, "Addons", addons)
	content := bytes.TrimRight(output.Bytes(), "\n")
	content = append(content, '\n')
	return content, serviceNames, nil
}

func writeServiceTable(
	output *bytes.Buffer,
	title string,
	definitions []*registry.ServiceDefinition,
) {
	fmt.Fprintf(output, "## %s\n\n", title)
	output.WriteString("| Service | Category | Activation | Launcher | Route auth | Application auth | Image input | Description |\n")
	output.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, definition := range definitions {
		name := code(definition.Metadata.Name)
		if definition.Metadata.Homepage != "" {
			name = fmt.Sprintf("[%s](%s)", name, definition.Metadata.Homepage)
		}
		auth := "Not routed"
		if definition.Routing.Enabled {
			auth = string(definition.Routing.Auth.Mode)
		}
		launcher := "Hidden"
		if presentation := definition.Presentation.Launcher; presentation != nil &&
			presentation.Enabled {
			launcher = presentation.Group
		}
		fmt.Fprintf(
			output,
			"| %s | %s | %s | %s | %s | %s | %s | %s |\n",
			name,
			code(string(definition.Metadata.Category)),
			escapeTable(serviceActivation(definition)),
			code(launcher),
			code(auth),
			code(serviceApplicationAuth(definition)),
			code(definition.Spec.Image.Repository+":"+definition.Spec.Image.Tag),
			escapeTable(definition.Metadata.Description),
		)
	}
	output.WriteString("\n")
}

func generatePresets(serviceNames map[string]bool) ([]byte, error) {
	collection, err := presets.LoadBuiltin()
	if err != nil {
		return nil, fmt.Errorf("load built-in presets: %w", err)
	}
	for _, preset := range collection.Presets {
		for _, addon := range preset.Addons {
			if !serviceNames[addon] {
				return nil, fmt.Errorf("preset %s references missing service %s", preset.Name, addon)
			}
		}
	}

	var output bytes.Buffer
	output.WriteString(generatedNotice)
	output.WriteString("# Embedded Preset Reference\n\n")
	fmt.Fprintf(
		&output,
		"The release binary contains **%d named addon presets**. Presets select "+
			"addons only; Plex and Jellyfin remain explicit project choices.\n\n",
		len(collection.Presets),
	)
	output.WriteString("| Preset | Title | Addons | Purpose |\n")
	output.WriteString("| --- | --- | --- | --- |\n")
	for _, preset := range collection.Presets {
		addons := make([]string, 0, len(preset.Addons))
		for _, addon := range preset.Addons {
			addons = append(addons, code(addon))
		}
		fmt.Fprintf(
			&output,
			"| %s | %s | %s | %s |\n",
			code(preset.Name),
			escapeTable(preset.Title),
			strings.Join(addons, ", "),
			escapeTable(strings.TrimSpace(preset.Description)),
		)
	}
	output.WriteString(
		"\nUser presets in `~/.config/sdbx/presets.yaml` may override these names " +
			"locally. The generated release reference intentionally ignores those " +
			"machine-specific overlays.\n",
	)
	return output.Bytes(), nil
}

func serviceActivation(definition *registry.ServiceDefinition) string {
	switch {
	case definition.Conditions.RequireAddon:
		return "Explicit addon or preset"
	case definition.Conditions.Always:
		return "Always"
	case definition.Conditions.RequireConfig != "":
		return "When " + definition.Conditions.RequireConfig
	default:
		return "Invalid activation selector"
	}
}

func formatValue(value any) string {
	if value == nil {
		return "null"
	}
	switch typed := value.(type) {
	case string:
		if typed == "" {
			return `""`
		}
		return typed
	case []string:
		if len(typed) == 0 {
			return "[]"
		}
		return "[" + strings.Join(typed, ", ") + "]"
	case bool:
		return strconv.FormatBool(typed)
	case int:
		return strconv.Itoa(typed)
	default:
		reflected := reflect.ValueOf(value)
		if reflected.Kind() == reflect.Slice && reflected.Len() == 0 {
			return "[]"
		}
		return fmt.Sprint(value)
	}
}

func markdownAnchor(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	var output strings.Builder
	lastHyphen := false
	for _, character := range value {
		switch {
		case character >= 'a' && character <= 'z',
			character >= '0' && character <= '9':
			output.WriteRune(character)
			lastHyphen = false
		case character == ' ' || character == '-' || character == '_':
			if !lastHyphen && output.Len() > 0 {
				output.WriteByte('-')
				lastHyphen = true
			}
		}
	}
	return strings.Trim(output.String(), "-")
}

func code(value string) string {
	if value == "" {
		return "`\"\"`"
	}
	return "`" + strings.ReplaceAll(value, "`", "\\`") + "`"
}

func escapeTable(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "|", "\\|")
	return strings.TrimSpace(value)
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}
