package integrate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/get-sdbx/sdbx/internal/config"
	"github.com/get-sdbx/sdbx/internal/registry"
	"github.com/get-sdbx/sdbx/internal/securefs"
)

var unpackerrSecretNames = map[string]string{
	"sonarr":   "unpackerr_sonarr_api_key",
	"radarr":   "unpackerr_radarr_api_key",
	"lidarr":   "unpackerr_lidarr_api_key",
	"whisparr": "unpackerr_whisparr_api_key",
}

// RenderUnpackerrEnvironment writes the generated, non-secret environment
// file and file-backed copies of enabled Arr API keys. Inactive copies are
// truncated so the Unpackerr container never retains a disabled service key.
func RenderUnpackerrEnvironment(
	cfg *config.Config,
	graph *registry.ResolutionGraph,
) error {
	if cfg == nil || graph == nil {
		return fmt.Errorf("Unpackerr generation requires config and graph")
	}
	configRoot := cfg.ConfigPath
	if configRoot == "" {
		configRoot = "./configs"
	}
	secretsRoot := cfg.SecretsPath
	if secretsRoot == "" {
		secretsRoot = "./secrets"
	}
	unpackerrRoot := filepath.Join(configRoot, "unpackerr")
	if err := securefs.EnsureDir(unpackerrRoot, 0o755); err != nil {
		return fmt.Errorf("prepare Unpackerr config directory: %w", err)
	}
	if err := securefs.EnsureDir(secretsRoot, 0o700); err != nil {
		return fmt.Errorf("prepare Unpackerr secrets directory: %w", err)
	}

	active := make(map[string]bool, len(unpackerrSecretNames))
	lines := []string{
		"# Generated by SDBX. Edit the service definitions, not this file.",
		"UN_FOLDER_0_PATH=/downloads",
	}
	for _, name := range []string{"sonarr", "radarr", "lidarr", "whisparr"} {
		resolved := graph.Services[name]
		if resolved == nil || !resolved.Enabled || resolved.FinalDefinition == nil {
			continue
		}
		integration := resolved.FinalDefinition.Integrations.Unpackerr
		if integration == nil || !integration.Enabled {
			continue
		}
		key, err := ReadArrAPIKey(cfg, name)
		if err != nil {
			return fmt.Errorf("read %s API key for Unpackerr: %w", name, err)
		}
		if key == "" {
			return fmt.Errorf("%s API key is unavailable for Unpackerr", name)
		}
		serviceURL, err := StableArrServiceURL(cfg, graph, name)
		if err != nil {
			return fmt.Errorf("resolve %s URL for Unpackerr: %w", name, err)
		}
		secretName := unpackerrSecretNames[name]
		if err := writeUnpackerrSecret(
			filepath.Join(secretsRoot, secretName+".txt"),
			[]byte(key),
		); err != nil {
			return err
		}
		active[name] = true
		lines = append(
			lines,
			integration.URLEnvVar+"="+serviceURL,
			integration.APIKeyEnvVar+"=filepath:/run/secrets/"+secretName,
			strings.TrimSuffix(integration.URLEnvVar, "URL")+"PATHS_0=/downloads",
		)
	}

	inactive := make([]string, 0, len(unpackerrSecretNames))
	for name := range unpackerrSecretNames {
		if !active[name] {
			inactive = append(inactive, name)
		}
	}
	sort.Strings(inactive)
	for _, name := range inactive {
		secretName := unpackerrSecretNames[name]
		if err := writeUnpackerrSecret(
			filepath.Join(secretsRoot, secretName+".txt"),
			nil,
		); err != nil {
			return err
		}
	}

	body := []byte(strings.Join(lines, "\n") + "\n")
	path := filepath.Join(unpackerrRoot, "sdbx.env")
	if err := securefs.WriteFileAtomic(path, body, 0o755, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func writeUnpackerrSecret(path string, value []byte) error {
	if err := securefs.WriteFileAtomic(path, value, 0o700, 0o644); err != nil {
		return fmt.Errorf("write Unpackerr secret %s: %w", path, err)
	}
	for index := range value {
		value[index] = 0
	}
	// #nosec G302 -- the private parent confines this bind-mounted, container-readable copy.
	if err := os.Chmod(path, 0o644); err != nil {
		return fmt.Errorf("repair Unpackerr secret %s permissions: %w", path, err)
	}
	return nil
}
